volumes:
  mssqldata:

services:
  database:
    container_name: uid2_selfserve_mssql
    # image: mcr.microsoft.com/mssql/server:2022-latest
    build:
      context: ./sqlServer
      dockerfile: SqlServerDockerfile
    ports:
      - '11433:1433'
    volumes:
      - mssqldata:/var/opt/mssql
    environment:
      ACCEPT_EULA: 'yes'
      MSSQL_SA_PASSWORD: 'D3velopmentP0'
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P D3velopmentP0 -C -Q 'SELECT 1'"]
      interval: 10s
      timeout: 10s
      retries: 5